<a href="https://colab.research.google.com/github/snehalsarkate/Python-and-Machine-Learning/blob/main/Snehal_Sarkate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


***Iris_dataset Machine Learning Problem :: Using libraries***



**Library Importing :**

In [ ]:
import numpy as np
import pandas as pd


**Data Exploring :**





In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris() 

where load_iris is the "function" : returning to the dictionary.

**Dataset :**

In [ ]:
print("Keys of iris_dataset :\n",format(iris_dataset.keys()))



Keys of iris_dataset :
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


**DESCR = Description :**

In [ ]:
print(iris_dataset['DESCR'][:199] + "\n ..")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictiv
 ..


Where [:199] is "Slicing Operator"
It can also be written as 
val = iris_dataset['DESCR']
start_val = val[:199]
print(start_val + "\n ...")

**Target names :**


In [ ]:
print("Target Names : ",format(iris_dataset['target_names']))

Target Names :  ['setosa' 'versicolor' 'virginica']


Target Names gives the name of the 3-classes which is to be classified using Machine Learning.

**Feature Names :**


In [ ]:
print("Feature Names : ",format(iris_dataset['feature_names']))

Feature Names :  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Feature names gives the features of the flowers which is to be classified.


**Type of Data :**


In [ ]:
print("Type of Data : ",format(type(iris_dataset['data'])))

Type of Data :  <class 'numpy.ndarray'>


Tpe of data is the type in which the 3-classes is determined.


**Shape of Data :**


In [ ]:
print("Shape of Data :",format(iris_dataset['data'].shape))

Shape of Data : (150, 4)


Shape of Data is the number of Data provided.


**Displaying First 5 columns of the Data :**


In [ ]:
print("First Five columns of the Data :\n ",format(iris_dataset['data'][:5]))

First Five columns of the Data :
  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
print("First Five rows of the Data :\n ",format(iris_dataset['data'][:5]))

First Five rows of the Data :
  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


**Type of Target :**


In [ ]:
print("Type of target : \n",format(type(iris_dataset['target_names'])))

Type of target : 
 <class 'numpy.ndarray'>


**Shape of Target :**



In [ ]:
print("Shape of target : \n",format(iris_dataset['target'].shape))

Shape of target : 
 (150,)


**Target :**


In [ ]:
print("Target :\n",format(iris_dataset['target']))

Target :
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


where 0= setosa, 1=versicolor and 2=virginica

**Machine Learing Model :**


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(
iris_dataset['data'],iris_dataset['target'],random_state=0)

**Train_Test_Split :**

In [ ]:
print("X_Train Shape :",format(x_train.shape))
print("Y_Train Shape :",format(y_train.shape))
print("X_Test Shape :",format(x_test.shape))
print("y_Train Shape :",format(y_test.shape))


X_Train Shape : (112, 4)
Y_Train Shape : (112,)
X_Test Shape : (38, 4)
y_Train Shape : (38,)


**KNeighbours :**


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**Predictions :**


In [ ]:
X_new = np.array([[1,0.2,2.9,5]])
print("X_new.shape :",format(X_new.shape))

X_new.shape : (1, 4)


**Prediction of taget :**


In [ ]:
Prediction = knn.predict(X_new)

print("Prediction :",format(Prediction))
print("Predicted target name :",
      format(iris_dataset['target_names'][Prediction]))

Prediction : [2]
Predicted target name : ['virginica']


In [ ]:
y_pred = knn.predict(x_test)
print("Test Set pres=dictions :",format(y_pred))


Test Set pres=dictions : [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [ ]:
print("Test Set score :",format(np.mean(y_pred == y_test)))

Test Set score : 0.9736842105263158
